language: node_js
node_js:
 - "5.7.1"
install:
 - npm install -g firebase-tools
 - npm install -g angular-cli
script:
 - echo "0"
after_success:
 - ng build --prod
 - firebase deploy --token "$FIREBASE_TOKEN"